Ukrposhta/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Ukrposhta.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Ukrposhta/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Ukrposhta.Pages
{
    public class IndexPageModel : PageModel
    {
        private readonly ILogger<IndexPageModel> _logger;

        public IndexPageModel(ILogger<IndexPageModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Ukrposhta/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Ukrposhta.Pages
{
    public class PrivacyPageModel : PageModel
    {
        private readonly ILogger<PrivacyPageModel> _logger;

        public PrivacyPageModel(ILogger<PrivacyPageModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

Ukrposhta/Pages/Reports.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Text;
using Ukrposhta.Entities;
using Ukrposhta.Models;
using Ukrposhta.Servises.Interfaces;

namespace Ukrposhta.Client.Pages
{
    public class ReportsPageModel : PageModel
    {
        private readonly IDepartmenService _departmenService;
        private readonly IReportService _reportService;
        private readonly IEmployeeService _emploeeService;

        [BindProperty]
        public int? DepartmentId { get; set; }
        public List<EmployeeModel> EmployeesList { get; set; }
        [BindProperty]
        public List<SelectListItem> DepartmentList { get; set; }
        [BindProperty]
        public SalaryReportModel SalaryReport { get; set; }
        [BindProperty]
        public EmployeeFilterModel? EmployeeFilter { get; set; }

        public ReportsPageModel(IDepartmenService departmenService, IReportService reportService, IEmployeeService employeeService)
        {
            _departmenService = departmenService;
            _reportService = reportService;
            _emploeeService = employeeService;

            EmployeesList = new List<EmployeeModel>();
            DepartmentList = new List<SelectListItem>();
        }

        public async Task OnGet()
        {
            try
            {
                await RefreshData();
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public async Task OnPostDepartmentSalary()
        {
            try
            {
                EmployeeFilter.DepartmentId = DepartmentId;
                await RefreshData();
                SalaryReport = await _reportService.GetDepartmentSalaryReport(DepartmentId.Value);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        public async Task<IActionResult> OnPostSaveFile(int id)
        {
            try
            {
                DepartmentId = id;
                EmployeeFilter.DepartmentId = DepartmentId;
                await RefreshData();

                SalaryReport = await _reportService.GetDepartmentSalaryReport(DepartmentId.Value);

                string filename = $"{SalaryReport.DepartmentName} Department Salary Report.txt";
                string content = $"{JsonConvert.SerializeObject(SalaryReport)} \r\n {JsonConvert.SerializeObject(EmployeesList)}";

                Byte[] buffer = Encoding.ASCII.GetBytes(content);

                return File(buffer, "application/text", filename);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        private async Task RefreshData()
        {
            if (EmployeeFilter == null)
            {
                EmployeesList = (await _emploeeService.GetAllAsync()).ToList();
            }

            if (EmployeeFilter != null)
            {
                EmployeesList = (await _emploeeService.GetAllFilteredAsync(EmployeeFilter)).ToList();
            }

            var departments = await _departmenService.GetAllAsync();

            DepartmentList.Add(new SelectListItem
            {
                Disabled = true,
                Selected = true
            });

            foreach (var department in departments)
            {
                DepartmentList.Add(new SelectListItem
                {
                    Value = department.Id.ToString(),
                    Text = department.Name
                });
            }
        }
    }
}

Ukrposhta/Pages/Index.cshtml
@page
@model IndexPageModel
@{
    ViewData["Title"] = "ГОЛОВНА";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean a tortor a est sagittis finibus. Proin id arcu lectus. In condimentum facilisis eros non scelerisque. Nulla venenatis ultricies varius. Etiam enim lectus, molestie in viverra ut, pretium in lorem. Donec id felis nibh. Sed vel egestas ipsum, vel hendrerit dui. Morbi vel nisi non quam tempor varius. Vivamus vel risus turpis. Sed ullamcorper turpis at dolor porttitor, quis volutpat nunc pellentesque. Praesent ultricies purus eleifend lectus consequat porttitor. Duis justo ex, rhoncus sit amet libero eget, pulvinar maximus odio. Curabitur dui quam, fermentum ut lobortis at, dapibus in massa. Nulla lectus risus, dignissim nec lobortis sed, placerat a risus. Fusce et felis maximus, pharetra mauris in, lacinia leo.</p>
</div>

Ukrposhta/Pages/Reports.cshtml
@page
@using Ukrposhta.Client.Pages
@model ReportsPageModel

@{
    ViewData["Title"] = "Report";
    var firstDataItem = Model.EmployeesList.FirstOrDefault();
}
<div class="row">
    <label class="col-md-3">Salary Report</label>
    <div class="col-md-6">
        <form asp-page-handler="DepartmentSalary" method="post">
            <label>Chose Department</label>
            <select asp-for="DepartmentId" asp-items="Model.DepartmentList" class="form-control"></select>
            <button class="btn btn-sm btn-primary">Get Salary Report</button>
        </form>
    </div>
    @if (Model.SalaryReport != null)
    {
        <div class="col-md-3">
            <p>Salary Summary</p>
            <div>
                <div> Department Name </div>
                @Html.DisplayFor(modelItem => Model.SalaryReport.DepartmentName)
                <div> Salary Sum </div>
                @Html.DisplayFor(modelItem => Model.SalaryReport.SalarySum)
                <div> Average Salary </div>
                @Html.DisplayFor(modelItem => Model.SalaryReport.SalaryAverage)
                <div> Employee Count </div>
                @Html.DisplayFor(modelItem => Model.SalaryReport.EmployeeCount)
                <div> Positions Count </div>
                @Html.DisplayFor(modelItem => Model.SalaryReport.PositionsCount)
            </div>
            <form asp-page-handler="SaveFile" asp-route-id="@Model.DepartmentId" method="post">
                <button class="btn btn-sm btn-primary">Save Report To .txt</button>
            </form>
        </div>
    }
</div>


@if (Model.EmployeesList != null && firstDataItem != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => firstDataItem.FullName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => firstDataItem.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => firstDataItem.Phone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => firstDataItem.DateOfBirth)
                </th>
                <th>
                    @Html.DisplayNameFor(model => firstDataItem.DateOfEmploiment)
                </th>
                <th>
                    @Html.DisplayNameFor(model => firstDataItem.Salary)
                </th>
                <th>
                    @Html.DisplayNameFor(model => firstDataItem.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => firstDataItem.Department)
                </th>
                <th>
                    @Html.DisplayNameFor(model => firstDataItem.Position)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.EmployeesList)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Phone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateOfBirth)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateOfEmploiment)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Salary)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Department.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Position)
                    </td>
                </tr>
            }
        </tbody>
    </table>
}